name: WEB Build & Deploy to Azure Static Web Apps

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: write # Muy importante para que Azure gestione los entornos de prueba

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4

      - name: Configurar Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile

      - name: Build Web Micro-frontends
        run: pnpm --filter "./apps/web-accounts..." --filter "./apps/web-shell..." build
        env:
          VITE_API_URL: true

      # Unimos los microfrontends igual que antes para que vivan en un solo sitio
      - name: Preparar carpeta final
        run: |
          mkdir -p deploy
          cp -r apps/web-shell/dist/* deploy/
          mkdir -p deploy/accounts
          cp -r apps/web-accounts/dist/* deploy/accounts/

      # DESPLIEGUE A AZURE
      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "deploy" # Aquí es donde dejamos los archivos unidos
          api_location: ""       # Si tuvieras una API de Azure Functions, iría aquí
          output_location: ""    # Lo dejamos vacío porque ya es el build final