name: Security & Quality Analysis (OWASP)

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  # Escaneo de Dependencias (pnpm audit)
  dependency-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: PNPM Audit (Vulnerabilidades en librerías)
        # Falla si encuentra vulnerabilidades de nivel 'high' o 'critical'
        run: pnpm audit --prod --audit-level high
  # Seguridad OWASP (Horusec)
  owasp-security-scan:
    runs-on: ubuntu-latest
    needs: [dependency-audit]
    steps:
      - uses: actions/checkout@v4
      - name: Horusec Scan (SAST OWASP Top 10)
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
          /usr/local/bin/horusec start -p="./" -e="true" -s="LOW, MEDIUM, INFO" -D --config-file-path="./horusec-config.json"
          