name: Security & Quality Analysis (OWASP)

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  # Seguridad OWASP (Horusec)
  owasp-security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Horusec Scan (SAST OWASP Top 10)
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
          
          # Explicación de flags según tu log:
          # -p: Directorio actual.
          # -e: Retorna código 1 (rompe el build) si encuentra algo.
          # -s: Ignora severidades. Para que falle en HIGH y CRITICAL, 
          #     le decimos que ignore LOW e INFO.
          # -D: Deshabilitar Docker (GitHub Runners ya tienen las herramientas instaladas 
          #     y correrlo sin docker es mucho más rápido).
          
          /usr/local/bin/horusec start -p="./" -e="true" -s="LOW, MEDIUM, INFO" -D"

  # 4. Análisis de Secretos (TruffleHog)
  secret-scan:
    runs-on: ubuntu-latest
    needs: [owasp-security-scan]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: TruffleHog (Detectar Keys y Passwords expuestos)
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --only-verified # Solo avisa si la llave encontrada es válida/real