name: Security & Quality Analysis (OWASP)

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  # Seguridad OWASP (Horusec)
  owasp-security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Horusec Scan (SAST OWASP Top 10)
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
          # Ejecuta el análisis y falla si hay severidades Críticas o Altas
          /usr/local/bin/horusec start -p="./" --high-severity-error="true" --critical-severity-error="true"

  # 4. Análisis de Secretos (TruffleHog)
  secret-scan:
    runs-on: ubuntu-latest
    needs: [dependency-audit]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: TruffleHog (Detectar Keys y Passwords expuestos)
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --only-verified # Solo avisa si la llave encontrada es válida/real